### ISSUE TITLE
Create the correlator handler

### ISSUE THREAD

**Issue by scizorman** [mao-wfs/maocontroller#1]
## Goal
To handle correlator in the main script

## Todo
- [x] Implement the function to start and stop correlation
- [x] Implement initializer of correlator
- [x] Implement the function to setup for IP addresses and subnet masks
  - [x] Output port
  - [x] NTP server

## Completion condition
Merge PR

## Note
Nothing
