### ISSUE TITLE
Create main controller

### ISSUE THREAD

**Issue by scizorman** [mao-wfs/maocontroller#3]
## Goal
To control MAO-WFS

## Todo
- [ ] #1 - Implement correlator handler
- [ ] #2 - Implement switch handler
- [ ] Synchronize `correlator` and `switch`

## Completion condition
Merge PR

## Note
Nothing
