### ISSUE TITLE
Dec 25 2018 -> Jan 31 2019 - Release Ver1.0!

### ISSUE THREAD

**Issue by scizorman** [mao-wfs/maocontroller#4]
## Sprint Goal
Release ver1.0!
- [ ] #1 - Implement the correlator handler
- [ ] #2 - Implement the switch handler
- [ ] #4 - Implement the main controller

## Note
Nothing
